steps: 
- id: pull-env
  name: 'gcr.io/cloud-builders/gsutil'
  args: [
    'cp', 'gs://envs_store_dev/cloudbuild-generator/.env', './cloudbuild-generator/.env']
- id: build-image
  name: "gcr.io/cloud-builders/docker"
  entrypoint: 'bash'
  args: [
    'build', '-t', 'eu.gcr.io/codematic-shared-environment/toolkit-cloudbuild-generator-sandbox:$SHORT_SHA', '-f', './codeblock-toolkit/Dockerfile', './cloudbuild-generator'
  ]
- id: push-image
  name: "gcr.io/cloud-builders/docker"
  args: [
    'push',
    'eu.gcr.io/codematic-shared-environment/toolkit-cloudbuild-generator-sandbox:$SHORT_SHA'
  ]
- id: deploy-image
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: [
    'run', 'deploy',
    'toolkit-cloudbuild-generator-sandbox', '--image', 'eu.gcr.io/codematic-shared-environment/toolkit-cloudbuild-generator-sandbox:$SHORT_SHA',
    '--region', 'europe-west1', '--allow-unauthenticated', '--cpu=2', '--memory=2Gi', '--cpu-boost', '--timeout=500s'
  ]
