steps: 
- id: pull-env
  name: 'gcr.io/cloud-builders/gsutil'
  args: [
    'cp', 'gs://envs_store_dev/cloudbuild-generator/.env', './generator/.env']
- id: build-image
  name: "gcr.io/cloud-builders/docker"
  args: [
    'build', '-t', 'eu.gcr.io/codematic-shared-environment/cloudbuild-generator-dev:$SHORT_SHA', '-f', './codeblock-toolkit/Dockerfile', './'
  ]
- id: push-image
  name: "gcr.io/cloud-builders/docker"
  args: [
    'push',
    'eu.gcr.io/codematic-shared-environment/cloudbuild-generator-dev:$SHORT_SHA'
  ]
- id: deploy-image
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: [
    'run', 'deploy',
    'cloudbuild-generator-dev', '--image', 'eu.gcr.io/codematic-shared-environment/cloudbuild-generator-dev:$SHORT_SHA',
    '--region', 'REGION', '--allow-unauthenticated', '--cpu=2', '--memory=2Gi', '--cpu-boost', '--timeout=500s'
  ]
